language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - cpanm --notest --quiet Dist::Zilla
  - dzil authordeps | cpanm --notest --quiet
install:
  - dzil listdeps | cpanm --notest
script:
  - dzil test --release
