---
artifacts:
    given:
        given: 1

    literal: 42

    class:
        class: Foo

    singleton_class:
        class: Foo
        scope: singleton

bags:
    bag:
        artifacts:
            bag_class:
                class: Foo
